- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: trailing-whitespace
    types: [python]
# yet another python formatter
- repo: git://github.com/pre-commit/mirrors-yapf
  rev: v0.30.0
  hooks:
  - id: yapf
    name: yapf
    types: [python]
    exclude: >
      (?x)^(
          docs/.*|
      )$
    args: ['-i']

- repo: local
  hooks:

  # prospector: collection of linters
  - id: pylint
    name: pylint
    entry: pylint
    types: [python]
    language: system
