version: '2'

services:
  bokeh:
    restart: always
    build: .
    image: discover-cofs:latest
    
    # Data is copied into the image at build time, so the following is not needed.
    # volumes:
    #  - './data:/project/discover-cofs/data'
    
    ports:
      - '3245:5006'
